/**
 * Created 07/12/2020
 * By: Omer Farkhand
 * Last Modified 07/12/2020
 * By: Omer Farkhand
 * 
 * Contributors: Omer Farkhand
 */

using System.Collections;
using UnityEngine;

/*
 * ParticleDestroyer destroys the particle effects generated by the EnemyGenerator script
 */
public class ParticleDestroyer : MonoBehaviour
{
    GameObject particle;

    // Start is called before the first frame update
    void Start()
    {
        particle = GameObject.Find("Respawn(Clone)");
        
    }

    // OnTriggerEnter detects all trigger collisions on entry
    private void OnTriggerEnter(Collider other)
    {
        // Condition checks if the colliding object has a Player tag
        if (other.gameObject.tag == "Player")
        {
            // Starts a timer then destroys the particle effect
            StartCoroutine(DestroyEffect());
        }
    }

    // DestroyEffect has a timer to destroy the particle effect
    IEnumerator DestroyEffect()
    {
        yield return new WaitForSeconds(2);
        Destroy(particle);
    }
}